# Generated by Django 3.0.5 on 2020-11-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
