# Generated by Django 3.0.5 on 2020-12-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='about',
            field=models.TextField(default='About not updated'),
            preserve_default=False,
        ),
    ]
