# Generated by Django 3.2.6 on 2021-11-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20201205_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='channel_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='qwerty*qwerty', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.TextField(default='qwerty*qwerty'),
        ),
        migrations.AddField(
            model_name='course',
            name='video_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
