# Generated by Django 3.2.6 on 2021-11-29 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_course_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
