# Generated by Django 3.2.6 on 2021-11-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20211129_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='expectations',
            field=models.TextField(default='qwerty*qwerty'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
