# Generated by Django 3.2.6 on 2021-11-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20211129_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.CharField(default='', max_length=100),
        ),
    ]
