# Generated by Django 3.0.5 on 2021-07-22 13:46

from django.db import migrations, models
import sayches.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sayches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pop',
            name='image',
            field=models.ImageField(upload_to='bla/', validators=[sayches.validators.mime_validator]),
        ),
    ]
